version = 0.1

[default.deploy.parameters]
stack_name = "day16-api-gateway-lambda"
resolve_s3 = true
s3_prefix = "day16-api-gateway-lambda"
region = "ap-northeast-1"
profile = "challenge-user"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-northeast-1"
